data:
    data_dir: 'DFKI DATASET'
    data_loader_workers: 0
    skeleton_path: 'DFKI DATASET/subject1_IdleLook-001.bvh'
    processed_data_dir: 'processed_data_DFKI'
    flip_bvh: true
    dataset: 'DFKI'
    exp_name: 'DFKI'

device:
    gpu_id: 0

model:
    batch_size: 32
    epochs: 2  #500
    loss_quat_weight: 1.20
    loss_root_weight: 1.0
    loss_pos_weight: 0.75
    loss_contact_weight: 0.05
    loss_global_quat: 0.02
    loss_discriminator_weight: 0.001
    loss_generator_weight: 0.00001
    target_noise: 0.5
    save_optimizer: False
    learning_rate: 0.001
    optim_beta1: 0.5
    optim_beta2: 0.9
    training_frames: 80
    window: 91 # +11
    
log:
    weight_save_interval: 1 #25

test:
    data_dir: 'DFKI DATASET'
    saved_weight_path: ''
    processed_data_dir: 'processed_data'
    test_frames: 80
    test_window: 90
    plot: false
    inference_batch_index: 25
