data:
    data_dir: 'ubisoft-laforge-animation-dataset/output/BVH'
    data_loader_workers: 0
    skeleton_path: 'ubisoft-laforge-animation-dataset/output/BVH/walk1_subject1.bvh'
    processed_data_dir: 'processed_data_original'
    flip_bvh: False

device:
    gpu_id: 1

model:
    batch_size: 128
    epochs: 500
    loss_quat_weight: 5.0
    loss_root_weight: 1.0
    loss_pos_weight: 1.0
    loss_contact_weight: 0.1
    loss_discriminator_weight: 0.0001
    loss_generator_weight: 0.000005
    target_noise: 0.5
    save_optimizer: False
    learning_rate: 0.001
    optim_beta1: 0.5
    optim_beta2: 0.9
    
log:
    weight_save_interval: 5

test:
    saved_weight_path: 'model_weights/curriculum'
    num_gifs: 30
    training_frames: 25
    plot: true
    inference_batch_index: 25