data:
    data_dir: 'AMASS/HumanEva'
    data_loader_workers: 0
    processed_data_dir: 'processed_data_humaneva_40'
    flip_bvh: false
    dataset: 'HumanEva'
    exp_name: 'HumanEva_40'

device:
    gpu_id: 0

model:
    batch_size: 32
    epochs: 500
    loss_quat_weight: 1.20
    loss_root_weight: 1.0
    loss_pos_weight: 0.75
    loss_contact_weight: 0.05
    loss_global_quat: 0.02
    loss_discriminator_weight: 0.001
    loss_generator_weight: 0.00001
    target_noise: 0.5
    save_optimizer: False
    learning_rate: 0.001
    optim_beta1: 0.5
    optim_beta2: 0.9
    training_frames: 40
    window: 51 # +11
    
log:
    weight_save_interval: 25

test:
    data_dir: 'AMASS/HumanEva'
    saved_weight_path: 'model_weights/HumanEva_80/trained_weight_200'
    processed_data_dir: 'processed_data_humaneva_80'
    test_frames: 80
    test_window: 90
    plot: false
    inference_batch_index: 25